[package]
name = "gladrl"
version = "0.0.6"
authors = ["Chris Rayner <dchrisrayner@gmail.com>"]

[dependencies]
rand = "0.3.0"
ncurses = "5.85.0"
csv = "1"
Inflector = "0.10.1"
zip = "0.5.0"
clippy = {version = "*", optional = true}
